CREATE TABLE `conversation` (
                                `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '会话ID',
                                `conversation_id` varchar(64) NOT NULL COMMENT '会话唯一标识',
                                `type` tinyint(1) NOT NULL COMMENT '会话类型：0-单聊，1-群聊',
                                `owner_id` bigint(20) NOT NULL COMMENT '会话所有者ID',
                                `target_id` bigint(20) NOT NULL COMMENT '目标ID（用户ID或群组ID）',
                                `unread_count` int(11) NOT NULL DEFAULT '0' COMMENT '未读消息数',
                                `last_message_id` varchar(64) DEFAULT NULL COMMENT '最后一条消息ID（MongoDB ObjectId）',
                                `last_message_content` varchar(500) DEFAULT NULL COMMENT '最后一条消息内容（冗余）',
                                `last_message_time` datetime DEFAULT NULL COMMENT '最后一条消息时间',
                                `last_sender_id` bigint(20) DEFAULT NULL COMMENT '最后一条消息发送者ID',
                                `last_sender_name` varchar(64) DEFAULT NULL COMMENT '最后一条消息发送者昵称（冗余）',
                                `is_top` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否置顶：0-否，1-是',
                                `is_mute` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否免打扰：0-否，1-是',
                                `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
                                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `idx_conversation_owner` (`conversation_id`,`owner_id`),
                                KEY `idx_owner_id` (`owner_id`),
                                KEY `idx_target_id` (`target_id`),
                                KEY `idx_owner_time` (`owner_id`, `last_message_time`),
                                KEY `idx_owner_top_time` (`owner_id`, `is_top`, `last_message_time`),
                                KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会话表';