CREATE TABLE `user` (
                        `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
                        `username` varchar(64) NOT NULL COMMENT '用户名',
                        `password` varchar(128) NOT NULL COMMENT '密码（加密存储）',
                        `nickname` varchar(64) DEFAULT NULL COMMENT '昵称',
                        `avatar` varchar(255) DEFAULT NULL COMMENT '头像URL',
                        `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
                        `email` varchar(64) DEFAULT NULL COMMENT '邮箱',
                        `gender` tinyint(1) DEFAULT '0' COMMENT '性别：0-未知，1-男，2-女',
                        `birth_date` date DEFAULT NULL COMMENT '出生日期',
                        `signature` varchar(255) DEFAULT NULL COMMENT '个性签名',
                        `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态：0-禁用，1-正常',
                        `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
                        `last_login_ip` varchar(64) DEFAULT NULL COMMENT '最后登录IP',
                        `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
                        `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                        `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `idx_username` (`username`),
                        KEY `idx_phone` (`phone`),
                        KEY `idx_email` (`email`),
                        KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';