local server = require "resty.websocket.server"
local cjson = require "cjson"

-- 创建WebSocket服务器对象
local wb, err = server:new({
    timeout = 5000,  -- 5s
    max_payload_len = 65535
})

if not wb then
    ngx.log(ngx.ERR, "WebSocket服务器创建失败: ", err)
    return ngx.exit(444)
end

-- 获取用户ID
local user_id = ngx.req.get_headers()["X-User-ID"]
if not user_id then
    ngx.log(ngx.ERR, "WebSocket连接缺少用户ID")
    return ngx.exit(401)
end

-- 记录用户会话
local user_sessions = ngx.shared.user_sessions
user_sessions:set(user_id, ngx.var.connection, 3600) -- 1小时过期

-- 发送欢迎消息
local welcome_msg = cjson.encode({
    type = "system",
    content = "WebSocket连接已建立",
    timestamp = ngx.time() * 1000
})

local bytes, err = wb:send_text(welcome_msg)
if not bytes then
    ngx.log(ngx.ERR, "发送欢迎消息失败: ", err)
    return ngx.exit(444)
end

-- 消息处理循环
while true do
    local data, typ, err = wb:recv_frame()
    if wb.fatal then
        ngx.log(ngx.ERR, "WebSocket连接已断开: ", err)
        break
    end

    if not data then
        if not string.find(err, "timeout", 1, true) then
            ngx.log(ngx.ERR, "WebSocket接收消息失败: ", err)
            break
        end
    elseif typ == "close" then
        -- 客户端关闭连接
        user_sessions:delete(user_id)
        break
    elseif typ == "ping" then
        -- 响应ping
        local bytes, err = wb:send_pong()
        if not bytes then
            ngx.log(ngx.ERR, "发送pong失败: ", err)
            break
        end
    elseif typ == "text" then
        -- 处理文本消息
        local ok, message = pcall(cjson.decode, data)
        if not ok then
            ngx.log(ngx.ERR, "解析消息失败: ", message)
        else
            -- 这里可以添加消息处理逻辑，例如转发到后端服务
            -- 示例：将消息转发到消息处理服务
            local http = require "resty.http"
            local httpc = http.new()

            local res, err = httpc:request_uri("http://im-message:8080/api/message/process", {
                method = "POST",
                body = cjson.encode({
                    user_id = user_id,
                    message = message
                }),
                headers = {
                    ["Content-Type"] = "application/json"
                }
            })

            if not res then
                ngx.log(ngx.ERR, "转发消息失败: ", err)
            end
        end
    end
end

-- 关闭WebSocket连接
wb:send_close()---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19935.
--- DateTime: 2025/5/27 12:34
---